### PR TITLE
fix(pipeline_resource): switch yaml to json conversion to yq to support anchors in different sections of the yaml (like the dedicated indicators section)

### LINKED ISSUE #152: [Bug]: Issue with `codefresh_pipeline` resource where `original_yaml_string` uses YAML anchors & aliases
### What happened?

In our pipeline definitions we're [using YAML anchors (and aliases) to avoid repetition](https://codefresh.io/docs/docs/pipelines/what-is-the-codefresh-yaml/#using-yaml-anchors-to-avoid-repetition).

When using a `codefresh_pipeline` resource where the file `original_yaml_string` contains YAML anchors and aliases the `apply` fails with:
> ```
> ╷
> │ Error: error while converting 'steps' YAML to JSON: yaml: unknown anchor 'my_common_envs' referenced
> │ 
> │   with codefresh_pipeline.indicators,
> │   on main.tf line 49, in resource "codefresh_pipeline" "indicators":
> │   49: resource "codefresh_pipeline" "indicators" {
> │ 
> ╵
> ```

The YAML pipeline definitions I'm using to validate this are the [examples in the documentation](https://codefresh.io/docs/docs/pipelines/what-is-the-codefresh-yaml/#using-yaml-anchors-to-avoid-repetition). So these work fine when configuring through the Codefresh console/GUI, and they also pass validation
> ```
> ❯ codefresh validate plain.yaml
> Yaml is valid!
> 
> ❯ codefresh validate indicators.yaml
> Yaml is valid!
> ```

### Version

Seems to be broken in `>= 0.4.0`, including current latest `0.10.1`
Works in `<= 0.3.1`

### Relevant Terraform Configuration

**`main.tf`**

```hcl
terraform {
  required_version = "1.9.5"

  backend "local" {}

  required_providers {
    codefresh = {
      source  = "codefresh-io/codefresh"
      version = "0.3.1"   # works
      #version = "0.4.0"  # broken
      #version = "0.10.1" # broken
    }
  }
}

provider "codefresh" {
  api_url = "${var.codefresh_api_url}/api"
  token   = var.codefresh_token
}

variable "codefresh_api_url" {
  description = "Codefresh authentication token"
  type        = string
}

variable "codefresh_token" {
  description = "Codefresh authentication token"
  type        = string
}

locals {
  codefresh_project_name = "testing"
}

resource "codefresh_pipeline" "plain" {

  name = "${local.codefresh_project_name}/example-plain"

  original_yaml_string = file("${path.module}/plain.yaml")

  spec {
    variables = {
      TIME = timestamp() # force update of resource on every plan/apply
    }
  }

}

resource "codefresh_pipeline" "indicators" {

  name = "${local.codefresh_project_name}/example-indicators"

  original_yaml_string = file("${path.module}/indicators.yaml")

  spec {
    variables = {
      TIME = timestamp() # force update of resource on every plan/apply
    }
  }

}
```

----------------

**`plain.yaml`**

```yaml
version: "1.0"
steps:
  preLoadDatabase:
    title: Loading Data
    image: alpine
    commands:
      - printenv
      - echo "Loading DB"
    environment: &my_common_envs
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASS=password
      - MYSQL_PORT=3351
  runTests:
    title: Integration tests
    image: alpine
    commands:
      - printenv
      - echo "Running tests"
    environment: *my_common_envs # Same MYSQL_HOST, MYSQL_USER etc.

```

----------------

**`indicators.yaml`**

```yaml
version: "1.0"

indicators:
  - environment: &my_common_envs
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASS=password
      - MYSQL_PORT=3351

steps:
  preLoadDatabase:
    title: Loading Data
    image: alpine
    commands:
      - printenv
      - echo "Loading DB"
    environment: *my_common_envs # Same MYSQL_HOST, MYSQL_USER etc.
  runTests:
    title: Integration tests
    image: alpine
    commands:
      - printenv
      - echo "Running tests"
    environment: *my_common_envs # Same MYSQL_HOST, MYSQL_USER etc.

```

### PR DESCRIPTION
**Pull request by ilia-medvedev-codefresh**
## What
closes #152 
## Checklist

* [ ] _I have read [CONTRIBUTING.md](https://github.com/codefresh-io/terraform-provider-codefresh/blob/master/CONTRIBUTING.md)._
* [ ] _I have [allowed changes to my fork to be made](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)._
* [ ] _I have added tests, assuming new tests are warranted_.
* [ ] _I understand that the `/test` comment will be ignored by the CI trigger [unless it is made by a repo admin or collaborator](https://codefresh.io/docs/docs/pipelines/triggers/git-triggers/#support-for-building-pull-requests-from-forks)._

### CODE REVIEW

File: codefresh/resource_pipeline.go [hunk 1]
```diff
@@ -1280,17 +1280,17 @@ func mapResourceToPipeline(d *schema.ResourceData) (*cfclient.Pipeline, error) {
 // This function is used to extract the spec attributes from the original_yaml_string attribute.
 // Typically, unmarshalling the YAML string is problematic because the order of the attributes is not preserved.
 // Namely, we care a lot about the order of the steps and stages attributes.
-// Luckily, the yj package introduces a MapSlice type that preserves the order Map items (see utils.go).
+// For this purpose we use yq that preserves the order or attributes when converting to json.
```
Comment (zarbis) [inline codefresh/resource_pipeline.go:1283]: "order of"

**Review by zarbis — APPROVED** [review]
